import { createSlice } from "@reduxjs/toolkit";

// Rare assets import
import rareIcon from "assets/images/rare-icon.png";
import rareBg from "assets/images/rare-background.jpg";
import rareGif from "assets/images/wolf-animation.gif";

// Epic assets import
import epicIcon from "assets/images/epic-icon.png";
import epicBg from "assets/images/epic-background.jpg";
import epicGif from "assets/images/unicorn-animation.gif";

// Legendary assets import
import legendaryIcon from "assets/images/legendary-icon.png";
import legendaryBg from "assets/images/legendary-background.jpg";
import legendaryGif from "assets/images/phoenix-animation.gif";

import { customAlphabet } from "nanoid";
const nanoid = customAlphabet("1234567890", 5);

const initialState = {
  data: [
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },
    {
      petId: nanoid(),
      type: "rare",
      typeIcon: rareIcon,
      bg: rareBg,
      gif: rareGif,
    },

    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "epic",
      typeIcon: epicIcon,
      bg: epicBg,
      gif: epicGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
    {
      petId: nanoid(),
      type: "legendary",
      typeIcon: legendaryIcon,
      bg: legendaryBg,
      gif: legendaryGif,
    },
  ].sort(() => Math.random() - 0.5),
};

export const petDetails = createSlice({
  name: "counter",
  initialState,
  reducers: {},
});

export const {} = petDetails.actions;

export default petDetails.reducer;
